---

- name: check if /etc/ipsec.d/openshift-cluster.conf already exist    
  stat: 
    path: /etc/ipsec.d/openshift-cluster.conf
  register: file_stats

- name: prompt for user whether to continue or not
  pause: prompt='File already exist! Press return to continue and overwrite. Press Ctrl+c and then "a" to abort'
  when: file_stats.stat.exists == true

- name: query for the local host common name in /etc/origin/node/server.crt
  #command: "openssl x509 -in /etc/origin/node/server.crt -subject -noout"
  command: "openssl x509 -in /etc/origin/node/generated_certs/{{ansible_fqdn}}.crt -subject -noout"
  register: cn_output

- debug:
    msg: "{{ cn_output.stdout | regex_search('(?<=CN=).*') }}"

- name: set the local host cert common name
  set_fact:
    openshift_aws_node_cn: "{{ cn_output.stdout | regex_search('(?<=CN=).*') }}"

- debug:
    msg: "{{ openshift_aws_node_cn }}"    

- name: get eth0 ipv4 address
  shell: ip addr show eth0 | grep 'inet\b' | awk '{print $2}' | cut -d/ -f1 
  register:  eth0_output
  when: openshift_aws_dual_nic

- name: set node ip 
  set_fact:
    openshift_aws_node_ip: "{{ eth0_output.stdout }}"       
  when: openshift_aws_dual_nic

- name: set default route as node ip
  set_fact:
    openshift_aws_node_ip: "%defaultroute"       
  when: not openshift_aws_dual_nic

- debug:
    msg: "{{ openshift_aws_node_ip }}"   

# populate and create configuration file from template
- name: create ocp configuration file name /etc/ipsec.d/openshift-cluster.conf
  template:
    dest: /etc/ipsec.d/openshift-cluster.conf
    src: "{{ role_path }}/templates/openshift-cluster.conf.j2"
    mode: "u=rw,g=r,o=r"
    force: yes


