---

- hosts: masters[0]
  gather_facts: false

  tasks:
  - name: Retrieve all config maps in openshift-node namespace 
    shell: oc get cm -n openshift-node | awk '{print $1}' | sed 1d
    register: openshift_node_config_maps

  - name: Output all config maps in openshift-node namespace
    debug:
      msg: "{{ item }}"
    loop:  "{{ openshift_node_config_maps.stdout_lines }}"

  - name: export config map files before making changes
    shell: oc get cm {{ item }} -n openshift-node -o yaml > /tmp/{{ item }}.yaml
    loop:  "{{ openshift_node_config_maps.stdout_lines }}"

  - name: get timestamp from the system
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: tstamp

  - name: backup the config map files before making changes
    become: yes
    copy:
      src: /tmp/{{ item }}.yaml
      dest: /tmp/{{ item }}.yaml.{{ tstamp.stdout[10:] }}
      remote_src: yes
      backup: yes  
    loop:  "{{ openshift_node_config_maps.stdout_lines }}"
  
  - name: Change mtu value to 8889 in config maps 
    replace:
      path: /tmp/{{ item }}.yaml
      regexp: 'mtu: 8951'
      replace: 'mtu: 8889'
    loop:  "{{ openshift_node_config_maps.stdout_lines }}"

  - name: please review the config map located in /tmp directory and confirm to continue 
    pause: prompt='Please review. Press return to continue to update node configuration. Press Ctrl+c and then "a" to abort'

  - name: updating mtu value in config map 
    shell: oc replace -f /tmp/{{ item }}.yaml -n openshift-node 
    loop:  "{{ openshift_node_config_maps.stdout_lines }}"
  