AWSTemplateFormatVersion: 2010-09-09
Description: Wrapper Template for Account Builder Approval Workflow
Parameters:
  sourcebucket:
    Description: "Source bucket where lambda function zip file is stored."
    Default : "organization-repo"
    Type: String
  EmailID:
    AllowedPattern: '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'
    ConstraintDescription: This is not a valid email id.
    Default: "aws-account-approvals@capgroup.com"
    Description: Enter Approvers Email ID
    MaxLength: '64'
    MinLength: '1'
    Type: String
Resources:
  CFApprovalWorkflow:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        sourcebucket: !Ref sourcebucket
        EmailID: !Ref EmailID
      Tags:
        - Key: cost-center
          Value: 524154
        - Key: ppmc-id
          Value: 69058
        - Key: usage-id
          Value: BB00000008
        - Key: toc 
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: ftdev
        - Key: sd-period
          Value: na   
        - Key: category
          Value: governance                                               
      TemplateURL: https://organization-repo.s3.amazonaws.com/servicecatalog/account-builder/scheduler/approval-workflow/CFApprovalWorkflow.yml