The following documentation is provided in the https://confluence.capgroup.com/display/CNTEN/Alertmanager+ServiceNow+Integration[Capital Group Confluence].

Alertmanager ServiceNow Integration
This document contains the steps for Alertmanager to integrate with ServiceNow.
alertmanager-webhook-servicenow is a Prometheus AlertManager webhook receiver that manages incidents from alerts.

Prerequisites
- A service account with permissions to read and update incidents.
- The Dev, QA or Prod instance of ServiceNow. https://{servicenow_instance_name}.service-now.com/api/cgm/incident
•	DEV instance: https://capitalgroupdev.service-now.com
•	QA instance: https://capitalgroupqa.service-now.com
•	Prod instance: https://capitalgroup.service-now.com
- The supported authentication to ServiceNow is through a service account (basic authentication through HTTPS).

Incident management workflow
The supported incident workflow is the following:
- Create a new incident if an alert is in the firing status 
- Return Incident Number after the incident is created in serviceNow

Installation
1. Log in to the OCP Cluster
oc login --token=<token> --server=https://api.ocp4-int-dev-west.csp.capgroup.com:6443

2. Pull the latest code from the bitbucket
git clone https://bitbucket.capgroup.com/scm/plat/alertmanager-webhook-servicenow.git
cd alertmanager-webhook-servicenow
git checkout develop
git pull

3. Create the alertmanager-webhook-servicenow image stream
oc new-build --binary --image-stream="openshift/golang:latest" --name alertmanager-webhook-servicenow

The alertmanager-webhook-servicenow image stream will be created.
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  selfLink: >-
    /apis/image.openshift.io/v1/namespaces/openshift-monitoring/imagestreams/alertmanager-webhook-servicenow
  resourceVersion: '311617974'
  name: alertmanager-webhook-servicenow
  uid: 97034532-49e0-40ea-8021-2899eb538531
  creationTimestamp: '2020-10-27T23:56:26Z'
  generation: 1
  namespace: openshift-monitoring
  labels:
    build: alertmanager-webhook-servicenow
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/openshift-monitoring/alertmanager-webhook-servicenow
  tags:
    - tag: latest
      items:
        - created: '2020-10-30T03:49:48Z'
          dockerImageReference: >-
            image-registry.openshift-image-registry.svc:5000/openshift-monitoring/alertmanager-webhook-servicenow@sha256:01a93f897b64639f2d780a100c871c306310369d95374e790113fe0fb71bde2f
          image: >-
            sha256:01a93f897b64639f2d780a100c871c306310369d95374e790113fe0fb71bde2f
          generation: 1
        - created: '2020-10-30T03:47:58Z'
          dockerImageReference: >-
            image-registry.openshift-image-registry.svc:5000/openshift-monitoring/alertmanager-webhook-servicenow@sha256:87603720d0cb240b2df08dd6672c4acf6aa2c8a87b8eb0f3e625b8475e2bace3
          image: >-
            sha256:87603720d0cb240b2df08dd6672c4acf6aa2c8a87b8eb0f3e625b8475e2bace3
          generation: 1
...


4. Create the alertmanager-webhook-service.yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2020-10-28T00:40:04Z
  labels:
    app: alertmanager-webhook-servicenow
  name: alertmanager-webhook-servicenow
  namespace: openshift-monitoring
  resourceVersion: "309338720"
  selfLink: /api/v1/namespaces/openshift-monitoring/services/alertmanager-webhook-servicenow
  uid: 8c481610-63e4-4a1e-b91b-a2d3f5bbe612
spec:
  clusterIP: 192.168.246.173
  ports:
  - name: 9877-tcp
    port: 9877
    protocol: TCP
    targetPort: 9877
  selector:
    app: alertmanager-webhook-servicenow
    deploymentconfig: alertmanager-webhook-servicenow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


5. Create the alertmanager-webhook-servicenow object
oc create -f alertmanager-webhook-servicenow.yaml

6. Start a new build from your local directory
oc start-build alertmanager-webhook-servicenow --from-dir=.

7. Deploy the new application
oc new-app alertmanager-webhook-servicenow 

8. Create a secret to hold the SERVICENOW_INSTANCE_NAME, SERVICENOW_USERNAME, SERVICENOW_PASSWORD
The secret name is secret-token-for-alertmanager-webhook-servicenow
 

apiVersion: v1
kind: Secret
metadata:
  name: secret-token-for-alertmanager-webhook-servicenow
stringData:
  SECRET_TOKEN: vPWps5E7KO8KPlljaD3eXED3f6jmLsV5mQ

9. Create the servicenow-config configmap 
$ oc create configmap servicenow-config --from-literal=enabled="true" --from-literal=caller_id="IP Sam" --from-literal=business_service=OpenShift --from-literal=category=Error --from-literal=contact_type=email --from-literal=assignment_group="PDS OpenShift Engineering-L3" --from-literal=assigned_to="Saroj Das" --from-literal=impact=1 --from-literal=urgency=1 --from-literal=cmdb_id=OpenShift --from-literal=template="IpControl New IP Range Template"

10. Validate the keys and values were populated in the servicenow-config configmap.
$ oc describe configmap servicenow-config
Name:         servicenow-config
Namespace:    openshift-monitoring
Labels:       <none>
Annotations:  <none>

Data
====
assignment_group:
----
PDS OpenShift Engineering-L3
business_service:
----
OpenShift
contact_type:
----
email
impact:
----
1
template:
----
IpControl New IP Range Template
urgency:
----
1
assigned_to:
----
Saroj Das
category:
----
Error
cmdb_id:
----
OpenShift
called_id:
----
IP Sam
Events:  <none>

11. Adjust the alertmanager-webhook-servicenow deployment config to use the secret for environment variable
oc edit dc alertmanager-webhook-servicenow
Add the following content to the deployment config yaml.
    spec:
      containers:
      - env:
        - name: SERVICENOW_INSTANCE_NAME
          valueFrom:
            secretKeyRef:
              key: SERVICENOW_INSTANCE_NAME
              name: secret-token-for-alertmanager-webhook-servicenow
        - name: SERVICENOW_USERNAME
          valueFrom:
            secretKeyRef:
              key: SERVICENOW_USERNAME
              name: secret-token-for-alertmanager-webhook-servicenow
        - name: SERVICENOW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SERVICENOW_PASSWORD
              name: secret-token-for-alertmanager-webhook-servicenow
        - name: CALLER_ID
          valueFrom:
            configMapKeyRef:
              key: caller_id
              name: servicenow-config
        - name: BUSINESS_SERVICE
          valueFrom:
            configMapKeyRef:
              key: business_service
              name: servicenow-config
        - name: CATEGORY
          valueFrom:
            configMapKeyRef:
              key: category
              name: servicenow-config
        - name: CONTACT_TYPE
          valueFrom:
            configMapKeyRef:
              key: contact_type
              name: servicenow-config
        - name: ASSIGNMENT_GROUP
          valueFrom:
            configMapKeyRef:
              key: assignment_group
              name: servicenow-config
        - name: ASSIGNED_TO
          valueFrom:
            configMapKeyRef:
              key: assigned_to
              name: servicenow-config
        - name: IMPACT
          valueFrom:
            configMapKeyRef:
              key: impact
              name: servicenow-config
        - name: URGENCY
          valueFrom:
            configMapKeyRef:
              key: urgency
              name: servicenow-config
        - name: CMDB_ID
          valueFrom:
            configMapKeyRef:
              key: cmdb_id
              name: servicenow-config
        - name: TEMPLATE
          valueFrom:
            configMapKeyRef:
              key: template
              name: servicenow-config
        - name: ENABLED
          valueFrom:
            configMapKeyRef:
              key: enabled
              name: servicenow-config

12. Roll out the deployment config change
oc rollout latest dc/alertmanager-webhook-servicenow

13. Go to the alertmanager-webhook-servicenow pod termninal tab. Type the 'set' command.
 
Verify that the environment variables were populated.
 
14. Expose the route
oc expose svc/alertmanager-webhook-servicenow

15. Export Alertmanager configuration
oc -n openshift-monitoring get secret alertmanager-main --template='{{ index .data "alertmanager.yaml" }}' |base64 -d > alertmanager.yaml

16. Add ServiceNow receiver in alertmanager.yaml and add the receiver to a route
...
routes:
- match:
    severity: critical
  receiver: servicenow-receiver

receivers:
- name: 'servicenow-receiver'
  webhook_configs:
  - url: "http://alertmanager-webhook-servicenow:9877/webhook"
    send_resolved: true

The list of available alert names can be found in Alerts and Monitoring for OCP4 Prod clusters
For alert name whitelisting, you can implement the following logic create servicenow tickets only for specific alerts:
- match_re:
    alertname: KubeSchedulerDown | KubePodCrashLooping | KubePodNotReady | KubeAPIDown | AlertmanagerConfigInconsistent
    severity: critical
  repeat_interval: 5m
  receiver: servicenow-receiver

17. Apply the Alertmanager configuration
oc -n openshift-monitoring create secret generic alertmanager-main --from-file=alertmanager.yaml --dry-run -o=yaml | oc -n openshift-monitoring replace secret --filename=-

18. Look at the logs of the alertmanager-webhook-servicenow pod. Verify that the webhook request is coming in and incident numbers were returned.
time="2020-10-30T03:50:03Z" level=info msg="Starting webhook(version=, branch=, revision=)" source="main.go:136"
time="2020-10-30T03:50:03Z" level=info msg="Build context(go=go1.11.5, user=, date=)" source="main.go:137"
time="2020-10-30T03:50:03Z" level=info msg="listening on: :9877" source="main.go:143"
Received alert Labels = condition=true  namespace=openshift-logging  prometheus=openshift-monitoring/k8s  severity=warning  alertname=KubeJobFailed  endpoint=https-main  instance=192.168.11.25:8443  job=kube-state-metrics  job_name=curator-1603266600  pod=kube-state-metrics-66b7564c4c-vgcj6  service=kube-state-metrics  , Annotations =message=Job openshift-logging/curator-1603266600 failed to complete.  , GeneratorURL = https://prometheus-k8s-openshift-monitoring.apps.ocp4-int-dev-west.csp.capgroup.com/graph?g0.expr=kube_job_failed%7Bjob%3D%22kube-state-metrics%22%2Cnamespace%3D~%22%28openshift-.%2A%7Ckube-.%2A%7Cdefault%7Clogging%29%22%7D+%3E+0&g0.tab=1, Fingerprint = 2c9bbddf04720232
KubeJobFailed https://prometheus-k8s-openshift-monitoring.apps.ocp4-int-dev-west.csp.capgroup.com/graph?g0.expr=kube_job_failed%7Bjob%3D%22kube-state-metrics%22%2Cnamespace%3D~%22%28openshift-.%2A%7Ckube-.%2A%7Cdefault%7Clogging%29%22%7D+%3E+0&g0.tab=1
map[result:map[message:Incident Created Successfully IncidentNumber:INC0587092 sys_id:b4e2b8af1b48209091af553f034bcb7c]]
map[sys_id:b4e2b8af1b48209091af553f034bcb7c message:Incident Created Successfully IncidentNumber:INC0587092]
...

19. Copy the sys_id from the log above. Go to the ServiceNow URL and verify that the incident is created:
https://capitalgroupdev.service-now.com/nav_to.do?uri=incident.do?sys_id=<sys_id>
For example, incident INC0587092: https://capitalgroupdev.service-now.com/nav_to.do?uri=incident.do?sys_id=b4e2b8af1b48209091af553f034bcb7c
20. During the maintanance window, you can disable the service now ticket creation by setting the enabled flag to false in the servicenow-config config map.
 
