AWSTemplateFormatVersion: 2010-09-09
Description: Deploy resources (in Master account) for autotagging CodeBuild automation
Resources:
  CodeBuildEventRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: Rule created to trigger a lambda function each time a CodeBuild Project is created
      EventPattern: 
        source:
        - aws.codebuild
        detail-type:
        - AWS API Call via CloudTrail
        detail:
          eventSource:
          - codebuild.amazonaws.com
          eventName:
          - CreateProject
      EventBusName: tagging
      Name: AutoTag-CodebuildProject-Event
      State: ENABLED
      Targets: 
        - 
          Arn: 
            Fn::GetAtt:
            - LFAutotagCodeBuild
            - Arn
          Id: LFAutotagCodeBuildProduction
  LFAutotagCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role to create CodeBuild Projects
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LFAutotagCodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:BatchGetProjects
                  - codebuild:UpdateProject
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - organizations:ListTagsForResource
                Resource: "*"
              - Sid: AssumeOrgRole
                Effect: Allow
                Action: 'sts:AssumeRole'
                Resource: 'arn:aws:iam::*:role/OrganizationAccountAccessRole'
  LFAutotagCodeBuildLG:
    Type: AWS::Logs::LogGroup
    DependsOn: LFAutotagCodeBuild
    DeletionPolicy: Retain
    Properties:
      LogGroupName:
        Fn::Join:
          - ''
          - - /aws/lambda/
            - Ref: LFAutotagCodeBuild
      RetentionInDays: 14
  CWToLFCodeBuildPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      FunctionName:
        Fn::GetAtt:
          - LFAutotagCodeBuild
          - Arn
      SourceArn:
        Fn::GetAtt:
          - CodeBuildEventRule
          - Arn
  LFAutotagCodeBuild:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function to tag CodeBuild Project
      Handler: index.lambda_handler
      Role: 
        Fn::GetAtt: 
          - LFAutotagCodeBuildRole
          - Arn
      Runtime: python3.7
      Timeout: '60'
      Code:
          ZipFile: |
            from __future__ import print_function
            import json
            import os
            import boto3
            import logging
            import time
            import datetime

            logger = logging.getLogger()
            logger.setLevel(logging.INFO)

            def set_resource_tags(credentials, project_name, account_id): 
              old_tags = {}
              new_tags = {}
              session = boto3.session.Session()
              codebuild_client = session.client(
                                  service_name='codebuild',
                                    aws_access_key_id=credentials['AccessKeyId'],
                                  aws_secret_access_key=credentials['SecretAccessKey'],
                                  aws_session_token=credentials['SessionToken']
                                )
              acc_tags = boto3.client('organizations').list_tags_for_resource(ResourceId=account_id)['Tags']          
              try:
                for each_property in codebuild_client.batch_get_projects(names=[project_name])['projects']:
                  old_tags=each_property['tags']
              except Exception as e:
                print(e)

              acc={i['Key']:i['Value'] for i in acc_tags}
              old={i['key']:i['value'] for i in old_tags}
              d={}
              d1={}
              required_tags=[]
              for i in old:
                  if i in acc:
                      d[i]=old[i]
              for i in acc:
                  if i not in d:
                      d[i]=acc[i]
              for i in old:
                  if i not in d:
                      d[i]=old[i]

              for i in d:
                  d1['key']=i
                  d1['value']=d[i]
                  required_tags.append(d1)
                  d1={}
       
        
              print('Tagging resource ' + project_name)
              try:
                response = codebuild_client.update_project(name=project_name,tags=required_tags)
                print(response)
                return True
              except Exception as e:
                print(e)
                return False
            def assume_role(account_id, account_role):
              sts_client = boto3.client('sts')
              role_arn = 'arn:aws:iam::' + account_id + ':role/' + account_role
              assuming_role = True
              while assuming_role is True:
                  try:
                      assuming_role = False
                      assumedRoleObject = sts_client.assume_role(
                          RoleArn=role_arn,
                          RoleSessionName="NewAccountRole"
                      )
                  except botocore.exceptions.ClientError as e:
                      assuming_role = True
                      print(e)
                      print("Retrying...")
                      time.sleep(60)

              # From the response that contains the assumed role, get the temporary
              # credentials that can be used to make subsequent API calls
              return assumedRoleObject['Credentials']

            def lambda_handler(event, context):
              try:
                region=event['detail']['awsRegion']
                detail=event['detail']
                account_id = detail['userIdentity']['accountId']
                eventname = detail['eventName']
                logger.info('region: ' + str(region))
                logger.info('eventName: ' + str(eventname))
                logger.info('detail: ' + str(detail))
        
                if not detail['requestParameters']:
                  logger.warning('No requestParameters found')
                  if detail['errorCode']:
                    logger.error('errorCode: ' + detail['errorCode'])
                  if detail['errorMessage']:
                    logger.error('errorMessage: ' + detail['errorMessage'])
                  return False
                
                if account_id == '848721808596':
                      return False
            
                if eventname == 'CreateProject':
                  project_arn=event['detail']['responseElements']['project']['arn']
                  project_name=event['detail']['responseElements']['project']['name']        
                  logger.info(project_name)
                else:
                  logger.warning('Not supported action')
                
                #Assume role of member account before tagging CodeCommit Repository
                account_role = 'OrganizationAccountAccessRole'
                credentials = assume_role(account_id, account_role)
    
                if project_name:
                  response = set_resource_tags(credentials, project_name, account_id)
                  return response
                else:
                  return False
              except Exception as e:
                logger.error('Error message: ' + str(e))
                return False
Outputs: {}