---
# tasks file for cg-all-splunk_uf

# this is used later to gate 6 tasks (currently), one if splunk_path.stat.exists=true,
# and the rest if that's false.
- name: Set splunk UF path /users/splunk/splunkforwarder
  stat:
    path: "{{ cg.install_directory }}/splunkforwarder"
  register: splunk_path
- fail:
    msg: "splunk is already installed" 
  when: splunk_path.stat.exists == true

# this is used later, in "Splunk set deploy-poll and Restart splunkd"
- name: Checking if deployment server set
  stat:
    path: /users/splunk/splunkforwarder/etc/system/local/deploymentclient.conf
  register: splunkds

- name: Splunk deployment server set
  debug:
    msg: 'Splunk Deployment Server is set'
  when: splunkds.stat.exists == true

- name: Creates {{ cg.working_directory }}
  file:
    path: "{{ cg.working_directory }}"
    state: directory
    recurse: yes 

- name: Install RPM {{ cg.binary }} to {{ cg.install_directory }}
  command: rpm -ivh --prefix={{ cg.install_directory }} http://{{ artifact_server }}/pkgdist/linux/splunk_uf/{{ cg.vers }}/{{ cg.binary }}
  when: splunk_path.stat.exists == false

- name: Add splunk user to secondary group 'syslog' to allow reading syslog files
  user:
    name: splunk
    groups: syslog

- name: Change owner and permission on directory {{ cg.install_directory }}
  file:
    path: "{{ cg.install_directory }}"
    owner: splunk
    group: splunk
    mode: "0774"
    state: directory
    recurse: yes
  when: splunk_path.stat.exists == false

- name: Start splunk {{ cg.install_directory }}/splunkforwarder/bin/splunk
  become: yes
  become_method: sudo
  shell: su - splunk -c "/users/splunk/splunkforwarder/bin/splunk start --accept-license"
  when: splunk_path.stat.exists == false

- name: Enable boot-start
  become: yes
  become_method: sudo
  shell: /users/splunk/splunkforwarder/bin/splunk enable boot-start -user splunk
  when: splunk_path.stat.exists == false

- name: Splunk set deploy-poll and Restart splunkd
  become: yes
  become_method: sudo
  shell: su - splunk -c "/users/splunk/splunkforwarder/bin/ splunk set deploy-poll {{ cg.deployment_server }}:{{ cg.deployment_server_port }} -auth {{ cg.user }}:{{ cg.password }} & /users/splunk/splunkforwarder/bin/splunk restart"
  when: splunkds.stat.exists == false