---
- fail:
    msg: "{{ item }} needs to be defined"
  when: item is not defined
  with_items:
  - atm_id

  - name: Create IAM role and trust policy 
    iam_role:
      name: "{{atm_id}}_EC2_Role"
      assume_role_policy_document: "{{lookup('file','{{ role_path }}/templates/ec2-trust-policy.json')}}"
      state: present

  - name: Assign a policy called CloudWatchLogsPolicy to Role
    iam_policy:
      iam_type: role
      iam_name: "{{atm_id}}_EC2_Role"
      policy_name: CloudWatchLogsPolicy
      policy_document: "{{lookup('file','{{ role_path }}/templates/cloudwatch-logs-policy.json')}}"
      state: present
