---

- include_vars: vars/main.yaml

- name: Check if cloudwatch log agent is already install
  stat: 
    path: /etc/init.d/awslogs
  register: awslogs_service

- debug:
    msg: "INFO: CloudWatch logs agent is already installed.  Skipping all setup tasks..."
  when: awslogs_service.stat.exists   

- name: Upload an initial cloudwatch log agent config file
  copy:
    dest: /tmp/awslogs.conf
    group: root
    mode: "u=rw,g=r,o=r"
    owner: root
    src: "{{ role_path }}/templates/awslogs.conf.j2"
  when: not awslogs_service.stat.exists

- name: Upload the cloudwatch log agent install
  copy:
    dest: /tmp/AgentDependencies.tar.gz
    group: root
    owner: root
    mode: "u=rw,g=r,o=r"
    src: "{{ role_path }}/files/AgentDependencies.tar.gz"
  when: not awslogs_service.stat.exists

- name: Upload the cloudwatch log installer
  copy:
    dest: /tmp/awslogs-agent-setup.py
    group: root
    owner: root
    mode: "u=rw,g=r,o=r"
    src: "{{ role_path }}/files/awslogs-agent-setup.py"
  when: not awslogs_service.stat.exists

- name: Extract cloudwatch log agent install
  command: tar xvf /tmp/AgentDependencies.tar.gz -C /tmp/
  when: not awslogs_service.stat.exists

- name: Execute cloudwatch log agent installer
  command: python /tmp/awslogs-agent-setup.py -n -r {{ my_region }} -c /tmp/awslogs.conf --dependency-path /tmp/AgentDependencies
  when: not awslogs_service.stat.exists

- name: Check if afadmin account exists 
  shell: egrep afadmin /etc/passwd
  ignore_errors: yes
  register: user_exists

- name: Change awslogs.conf file permision
  file:
    path: /var/awslogs/etc/awslogs.conf
    owner: afadmin
    group: root
    mode: "u=rw,g=r,o=r"
  when: 
    - user_exists.rc == 0
    - awslogs_service.stat.exists
    
- name: Check if afadmin sudoers exists before sudo setup
  stat: 
    path: /etc/sudoers.d/afadmin
  register: sudoers_exists 

- name: Add sudo access to allow afadmin to stop/start/restart awslogs service 
  copy:
    content: |
      Defaults !requiretty 
      afadmin         ALL=NOPASSWD:/usr/sbin/service awslogs *
    dest: /etc/sudoers.d/afadmin
    force: no
    group: root
    owner: root
    mode: "u=r,g=r,o="
  when: 
    - user_exists.rc == 0
    - not sudoers_exists.stat.exists
    - awslogs_service.stat.exists

- debug:
    msg: "INFO: afadmin account does not exist.  Skipping sudo access setup..."
  when: user_exists.rc != 0