AWSTemplateFormatVersion: 2010-09-09
Description: Organization Tagging NonCompliance Config Rule Stack
Resources:
  OrganizationConfigRule:
      Type: "AWS::Config::OrganizationConfigRule"
      Properties:
          OrganizationConfigRuleName: "OrganizationConfigRuleRequiredTags"
          OrganizationManagedRuleMetadata:
              RuleIdentifier: REQUIRED_TAGS
              Description: "Check for untagged resources rule for the entire organization"
              InputParameters: >- 
                { 
                  "tag1Key" : "cost-center", 
                  "tag2Key" : "usage-id",
                  "tag3Key" : "ppmc-id", 
                  "tag4Key" : "toc", 
                  "tag5Key" : "exp-date", 
                  "tag6Key" : "env-type"
                }
              ResourceTypesScope:
                - "AWS::DynamoDB::Table"
                - "AWS::EC2::Instance"
                - "AWS::EC2::Volume"
                - "AWS::ElasticLoadBalancing::LoadBalancer"
                - "AWS::ElasticLoadBalancingV2::LoadBalancer"
                - "AWS::RDS::DBInstance"
                - "AWS::RDS::DBSnapshot"
                - "AWS::Redshift::Cluster"
                - "AWS::Redshift::ClusterSnapshot"
                - "AWS::S3::Bucket"
                - "AWS::Lambda::Function"
          ExcludedAccounts:
            - "405968000261"
            - "659392342863"
            - "378415543992"
            - "932860924500"
            - "067923858542"
            - "328097608792"
            - "210961756523"
            - "050843294547"
            - "982354747870"
            - "114553513249"
            - "757019876063"
            - "942153875752"