AWSTemplateFormatVersion: 2010-09-09
Description: Baseline config service setup for new account
Parameters:
  ConfigBucketName:
    Default: 111417557820-all-acct-config-logs
    Type: String
    Description: default bucket used from sec foundation account
  ConfigLogName:
    Type: String
    Description: config log name of the new account created

Resources:
  ConfigRecorder:
    Type: 'AWS::Config::ConfigurationRecorder'
    Properties:
      Name: default
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
      RoleARN: !Join 
        - ''
        - - 'arn:aws:iam::'
          - !Ref 'AWS::AccountId'
          - ':role/ConfigRecorderRole'
  DeliveryChannel:
    Type: 'AWS::Config::DeliveryChannel'
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Six_Hours
      S3BucketName: !Ref ConfigBucketName
      S3KeyPrefix: !Ref ConfigLogName