AWSTemplateFormatVersion: 2010-09-09
Description: Wrapper Template for CFAccountConfigService
Parameters:
  ConfigBucketName:
    Default: 111417557820-all-acct-config-logs
    Type: String
    Description: default bucket used from sec foundation account
  ConfigLogName:
    Type: String
    Description: config log name of the new account created
Resources:
  CFAccountConfigService:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        ConfigBucketName: !Ref ConfigBucketName
        ConfigLogName: !Ref ConfigLogName
      Tags:
        - Key: cost-center
          Value: 524154
        - Key: ppmc-id
          Value: 69058
        - Key: usage-id
          Value: BB00000008
        - Key: toc 
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: prd
        - Key: sd-period
          Value: na   
        - Key: category
          Value: governance                                               
      TemplateURL: https://organization-repo.s3.amazonaws.com/acctautomation/CFAccountConfigService.yml