AWSTemplateFormatVersion: 2010-09-09
Description: GuardDuty Onboarding for a new account
Parameters:
  sourceBucket:
    Default: na  
    Type: String
Resources:
  LFGuardDutyOnboard:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref sourceBucket
        S3Key: "acctautomation/LFEnableGuardDuty.zip"
      Description: Lambda Function to enable Guard Duty within new account
      Handler: LFEnableGuardDuty.lambda_handler
      Role: !GetAtt 'LFGuardDutyOnboardRole.Arn'
      Runtime: python3.8
      Timeout: '120'
  LFGuardDutyOnboardLG:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: LFGuardDutyOnboard
    Properties:
      LogGroupName:
        'Fn::Join':
          - ''
          - - /aws/lambda/
            - Ref: LFGuardDutyOnboard
      RetentionInDays: 14
  LFGuardDutyOnboardRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AccountVending-LFGuardDutyOnboardRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LFGuardDutyOnboardPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: '*'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AWSOrganizationsFullAccess'
      - 'arn:aws:iam::aws:policy/AmazonGuardDutyFullAccess'

Outputs:
  LFGuardDutyOnboardArn:
    Value: !GetAtt LFGuardDutyOnboard.Arn