# this role is to collect all the data about vpc in a region
# set facts for important Ids and for a VPC
# find vpc id and cidr block by region and account
---
- name: VPC facts
  ec2_vpc_net_facts:
    region:   "{{aws_region}}"
  register: vpc_facts

- name: set fact vpc(s) main info - ID:CIDR block
  set_fact:
    vpc_info:  "{{vpc_info | default({}) | combine({vpc_facts.vpcs[vpcs_idx].vpc_id:vpc_facts.vpcs[vpcs_idx].cidr_block})}}"
  loop: "{{vpc_facts.vpcs}}"
  loop_control:
    index_var:  "vpcs_idx"

- name: VPC subnet facts
  ec2_vpc_subnet_facts:
    filters:
      vpc-id:   "{{item.key}}"
  with_dict:  "{{vpc_info}}"
  register:   vpc_subnet_facts

- debug:
    msg:  "{{item.subnets[subnet_idx].subnet_id}}"
  loop:  "{{vpc_subnet_facts.results}}"
  loop_control:
    index_var:  "subnet_idx"

    

  
  


