---

###
# start of block for OCP int-prd us-west-1
###
openshift_aws_ssh_key_name: ocp-int-prd-us-west-1
openshift_aws_rootenc_ami: ami-078bc28dc36a28246
openshift_aws_volume_kms_key_id: 06530f5b-be53-4293-8324-cbfcd310737a
openshift_aws_s3_kms_key_id: 06530f5b-be53-4293-8324-cbfcd310737a

openshift_aws_clusterid: vpc1-us-west-1-ocp-int-prd
openshift_aws_region: us-west-1
openshift_aws_env_type: prd

# define instance types
openshift_aws_ec2_control_instance_type: t2.medium
openshift_aws_ec2_master_instance_type: m5.2xlarge
openshift_aws_ec2_app_instance_type: m4.2xlarge
openshift_aws_ec2_infra_instance_type: m5.2xlarge

# misc flags
openshift_aws_dual_nic: False
openshift_aws_external_facing: False
nvme: true

# subnet information
openshift_aws_control_host_subnet: 
  - { admin_subnet: subnet-082d83de131751cca, az: us-west-1a } 

openshift_aws_admin_subnet_1: 
  - { subnet: subnet-082d83de131751cca, az: us-west-1a, count: 1 }
openshift_aws_admin_subnet_2:
  - { subnet: subnet-07a9cdb6a08d0d07a, az: us-west-1b, count: 1 }
openshift_aws_admin_subnet_3:
  - { subnet: subnet-013ab12b1e9fc90a9, az: us-west-1b, count: 1 }

openshift_elb_internalsubnets:
  - subnet-0ee59a3f121e8624a
  #- subnet-028e6ca41e2f414bb
  - subnet-0a0f6f2cfa4c40202

# openshift tagging
openshift_aws_kubernetes_tag_id: prod1-uswest1

openshift_aws_resource_tags:
  Name: "{{ openshift_aws_resource_type }}"
  usage-id: "{{ openshift_aws_atm_id }}"
  cost-center: "{{ openshift_aws_cost_center }}"
  sec-profile: normal
  exp-date: 99-00-9999
  sd-period: na
  p-id: "{{ openshift_aws_ppmc_id }}"
  env-type: "{{ openshift_aws_env_type }}"
  cloud-dependency: cloudonly
  app-type: "{{ openshift_aws_resource_type }}"
  kubernetes.io/cluster/cluster-INT-PRD: "{{ openshift_aws_kubernetes_tag_id }}"

#
# the following section contains variables to create the inventory configuration file
#
# define the internal master hostname
# ex. ocp-console-int.<env>-<nad, digital, etc.>-<usw1, use1>-aws.csp.capgroup.com
openshift_aws_internal_master_vip: ocp-console-int.prd-int-usw1-aws.csp.capgroup.com
# define the master hostname: 
# ex. ocp-console<env>-<nad, digital, etc.>-<usw1, use1>-aws.csp.capgroup.com 
openshift_aws_master_vip: ocp-console.prd-int-usw1-aws.csp.capgroup.com
# define the the default master subdomain
# ex. apps.<env>-<nad, digital, etc.>-<usw1, use1>-aws.csp.capgroup.com
openshift_aws_router_vip: .apps.prd-int-usw1-aws.csp.capgroup.com
# define the EBS availability zone for loggging
# ex. us-west-1a 
openshift_aws_logging_ebs_zone: us-west-1a
# define the EBS availability zone for metrics
# ex. us-west-1c 
openshift_aws_metric_ebs_zone: us-west-1b
# define the s3 bucket name
# ex. ocp-capgroup-<project name>-<env>-<region>
openshift_aws_s3_bucket_name: ocp-capgroup-int-prd-west1
openshift_aws_s3_bucket_region: "{{ openshift_aws_region }}"
openshift_aws_cluster_name: "{{ openshift_aws_kubernetes_tag_id }}" 

#
# post config IPSec variables
#
openshift_aws_env: int-prd-us-west-1
openshift_create_and_copy_cluster_conf: True
openshift_create_policies: True
openshift_copy_policies: True
openshift_configure_iptables: True

openshift_aws_s3_access_key: AKIAJWVTR6RA4HRSVVQA
openshift_aws_s3_secret_key: 
openshift_aws_ec2_access_key: AKIAIKD4LOCWT2ALV4TA
openshift_aws_ec2_secret_key: 

#AWS Resource Name
aws_controlhost_type: OCP Control Host
aws_masterhost_type: OCP Master Host
aws_infrahost_type: OCP Infra Host
aws_apphost_type: OCP App Host
aws_loadbalancer_type: OCP Load Balancer



#Outcold Tag
outcold_cluster_tag_key: prod-int-usw1-aws.cluster
outcold_appnode_tag_key: prod-int-usw1-aws.appnode

####
# end of block for OCP int-prd-us-west-1
###

