---
#Region 
aws_region: "us-east-1"

# vpc info - Pre prod
vpc_name: "vpc2_nadprod"
vpc_cidr: "10.211.80.0/22"
account_name: "nad-prod"       # use AWS account name w/o the AWS in lower case

# Tags values:
#   vpc tag values
resource_usage_id: "network"
atm_id: ""
p_id: ""
cost_center: "524035"
env_type: "nad-prod"


#   subnet tag values
subnet_atm_id: ""
subnet_p_id: ""
subnet_cost_center: "524035"
subnet_env_type: "nad-prod"
subnet_usage_id: "network-private"    #use "network-public" for public subnet

#AZ-Subnets
#this section describes all the subnets and set up index and sname(shortname) to form the subnet name later. 
#changing the field value without "{{value}}" will not require changing script
#adding more keys will require changing the script

vpc_private_subnets:  
  private_1:
    az_name:  "{{aws_region}}a"
    cblk:     "10.211.80.32/27"
    cnt:      "1"
    sname:    "Internal_ALB"
  private_2:
    az_name:  "{{aws_region}}b"
    cblk:     "10.211.80.96/27"
    cnt:      "2"
    sname:    "Internal_ALB"
  private_3:
    az_name:  "{{aws_region}}c"
    cblk:     "10.211.80.160/27"
    cnt:      "3"
    sname:    "Internal_ALB"
  private_4:
    az_name:  "{{aws_region}}a"
    cblk:     "10.211.80.192/26"
    cnt:      "4"
    sname:    "ocpadmin"
  private_5:
    az_name:  "{{aws_region}}a"
    cblk:     "10.211.81.0/26"
    cnt:      "5"
    sname:    "ocpcluster"
  private_6:
    az_name:  "{{aws_region}}b"
    cblk:     "10.211.81.64/26"
    cnt:      "6"
    sname:    "ocpadmin"
  private_7:
    az_name:  "{{aws_region}}b"
    cblk:     "10.211.81.128/26"
    cnt:      "7"
    sname:    "ocpcluster"
  private_8:
    az_name:  "{{aws_region}}c"
    cblk:     "10.211.81.192/26"
    cnt:      "8"
    sname:    "ocpadmin"
  private_9:
    az_name:  "{{aws_region}}c"
    cblk:     "10.211.82.0/26"
    cnt:      "9"
    sname:    "ocpcluster"
  private_10:                     #app-dbsubnets 1 - to be used for Nadia and other applications
    az_name:  "{{aws_region}}a"
    cblk:     "10.211.82.64/26"
    cnt:      "10"
    sname:    "app_db"

vpc_public_subnets:     #Public subnets
  public_1:
    az_name:  "{{aws_region}}a"
    cblk:     "10.211.80.0/27"
    cnt:      "1"
    sname:    "External_ALB"    
  public_2:
    az_name:  "{{aws_region}}b"
    cblk:     "10.211.80.64/27"
    cnt:      "2"
    sname:    "External_ALB"
  public_3:
    az_name:  "{{aws_region}}c"
    cblk:     "10.211.80.128/27"
    cnt:      "3"
    sname:    "External_ALB"

# Security groups - standards for any vpc. Any other security groups needed at a later date can be added here using the same format.
vpc_security_groups:
  - name: nad-prod-sg-adm
    description:  "SSH to ocp"   # shouldn't this be adminE
    rules:
      - proto:  "tcp"
        cidr_ip:   "10.0.0.0/8"     #this need to narrow down to userland subnets
        ports:
          - 22
          - 3389
      - proto: "icmp"
        cidr_ip:  10.0.0.0/8
        from_port:  8
        to_port:    0
    rules_egress: 
      - proto:  "udp"
        cidr_ip: 
          - "10.32.2.245/32"
          - "10.92.6.136/32"
          - "10.16.5.186/32"
        ports:  "123"
      - proto:  "icmp"
        cidr_ip:
          - 10.0.0.0/8
        from_port:  8
        to_port:    0
      - proto: "tcp" 
        cidr_ip:
          - 10.21.154.64/26
        ports:
          1590

  - name: SLM-access-from-CGProd
    description:  "Allow SSH, WinRM, SMB from CG SLM"
    rules:
      - proto:  "tcp"
        cidr_ip: 
          - "10.92.114.82/32"
          - "10.18.120.50/32"
        ports:
          - 22
          - 5986
          - 445
    rules_egress: ""
  - name:  Allow-web-traffic-from-to-CG
    description:  "Allow web traffic from/to CG"
    rules:
      - proto: "tcp"
        cidr_ip:  "10.0.0.0/8"    #need to narrow down to what server zones from CG
        ports:
          - 80
          - 8080
          - 443
    rules_egress:
      - proto: "tcp"
        cidr_ip:  "0.0.0.0/0"   #need to narrow down to what server zones
        ports:
          - 443
  - name: Allow-SQL-Management-From CG
    description:  "Allow SQL Management from CG"
    rules:
      - proto: "tcp"
        cidr_ip:  "10.0.0.0/8"  #need to narrow this to Admin E or userland
        ports:
          - 1590
          - 1434
    rules_egress: ""

# DHCP Option sets:
dhcp_options_set:
  - dnsname:  "us-west-1.compute.internal"
    dns_servers:
      - 10.211.1.136
      - 10.211.1.172
      - 10.0.0.11
      - 10.0.0.12
    ntp_servers:
      - 10.30.2.245
      - 10.92.6.136
      - 10.16.5.186

#Gateways options:
public_facing: "true"      # Does this VPC allow Internet facing traffic and contain public subnet
direct_connect: "true"      # Does this VPC connect to CG via DirectConnect 
VPN_connect:    "false"     # This should be false if using direct connect instead







        











