---
# roles/vpc/tasks/main.yml
# Create a VPC - This playbook create 1 VPC
- name: Create vpc
  ec2_vpc_net:
    name:           "{{vpc_name}}-{{aws_region}}-{{account_name}}"
    cidr_block:     "{{vpc_cidr}}"
    region:         "{{aws_region}}"
    state:          "present"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags:
      usage-id: "{{resource_usage_id}}"
      sec-profile: "{{sec_profile}}"
      exp-date: "{{exp_date}}"
      sd-period: "{{sd_period}}"
      cloud-dependency: "{{cloud_dependency}}"
      atm-id: "{{atm_id}}"
      p-id: "{{p_id}}"
      cost-center: "{{cost_center}}"
      env-type: "{{env_type}}"
  register: create_vpc

#return vpc-id for subnets creation next
- name:  save VPC_id
  set_fact:
    vpcid: "{{create_vpc.vpc.id}}"

#set custom dhcp-options set
- name: set dhcp option for vpc
  ec2_vpc_dhcp_option:
    domain_name:    "{{item.dnsname}}"
    region:         "{{aws_region}}"
    dns_servers:    "{{item.dns_servers}}"
    ntp_servers:    "{{item.ntp_servers}}"
    state:          "present"
    vpc_id:         "{{vpcid}}"
    delete_old:     "False"
    tags:
        usage-id: "{{resource_usage_id}}"
        exp-date: "{{exp_date}}"
        sd-period: "{{sd_period}}"
        cloud-dependency: "{{cloud_dependency}}"
        atm-id: "{{atm_id}}"
        p-id: "{{p_id}}"
        cost-center: "{{cost_center}}"
        env-type: "{{env_type}}"
  with_items:     "{{dhcp_options_set}}"
  register: create_dhcpoptions
  when: dhcp_options_set is defined

- name: save dhcp option id
  set_fact:
    dhcpoptid:   "{{create_dhcpoptions.results}}"
  when: dhcp_options_set is defined    




