AWSTemplateFormatVersion: 2010-09-09
Description: Create StackSet Execution Role Permissions
Parameters:
  EnvironmentType:
    Default: ftdev
    Type: String
    AllowedValues: 
      - ftdev
      - dev
      - qa
      - prod
Resources:
  StackSetExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Tags:
        - Key: ppmc-id
          Value: '69058'
        - Key: cost-center
          Value: '524154'
        - Key: usage-id
          Value: BB00000008
        - Key: toc
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: !Ref EnvironmentType
        - Key: sd-period
          Value: na
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: >-
                arn:aws:iam::848721808596:role/AWSCloudFormationStackSetAdministrationRole
            Action: 'sts:AssumeRole'
            Condition: {}
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - 'arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        - 'arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess'
        - 'arn:aws:iam::aws:policy/AWSCloudFormationFullAccess'
      Policies:
        - PolicyName: TagNonComplianceStackSetAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'lambda:InvokeFunction'
                  - 'config:*'
                  - 'states:StartExecution'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Sid: VisualEditor1
                Effect: Allow
                Action: 'logs:CreateLogGroup'
                Resource: 'arn:aws:logs:*:*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3349c1e0-afde-4347-9e1a-7a58f9d7e91d