AWSTemplateFormatVersion: 2010-09-09
Description: WrapperTemplate
Resources:
  TagNonCompliance:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Tags:
        - Key: cost-center
          Value: 524154
        - Key: ppmc-id
          Value: 69058
        - Key: usage-id
          Value: BB00000008
        - Key: toc 
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: ftdev
        - Key: sd-period
          Value: na                                                  
      TemplateURL: https://tag-noncompliance.s3-us-west-1.amazonaws.com/tag-noncompliance.yml