AWSTemplateFormatVersion: 2010-09-09
Description: Account Builder Template for developer AWS accounts.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterLabels:
      BudgetLimit:
        default: Budgeted spend per month
      AlertThreshold1:
        default: 'First threshold at which an alert notification is sent out by email'
      AlertThreshold2:
        default: 'Second threshold at which an alert notification is sent out by email'
      AlertThreshold3:
        default: 'Third threshold at which an alert notification is sent out by email'
      NotificationEmail:
        default: Provide the email address/distribution where the alert should be sent 

    ParameterGroups:
      - Label:
          default: Required information to provision the AWS account
        Parameters:
          - RequestorInitials
          - CostCenter
          - PPMCId
          - UsageID
          - TOC
          - VPCCIDRBlockEast1

      - Label:
          default: Monthly budget approved for the account
        Parameters:
          - BudgetLimit
          - AlertThreshold1
          - AlertThreshold2
          - AlertThreshold3
          - NotificationEmail
        
Parameters:

  RequestorInitials:
    Description: "Initials of the individual requesting the account"
    Type: String
    AllowedPattern: "^[A-Z]{3,7}$"
    ConstraintDescription: "Initials can only contain upper case letters"

  VPCCIDRBlockEast1:
    Description: "VPC CIDR block for west-1 region, e.g 10.220.7.0/25"
    Default : "na"
    Type: String

  CostCenter:
    Description: "Cost Center, please enter valid 6 digit number"
    Type: String
    AllowedPattern: "^[0-9]{6}$"
    ConstraintDescription: "Cost Center is a six digit number"

  PPMCId:
    Description: "PPMC ID, please enter a valid 5 digit number"
    Type: String
    AllowedPattern: "^[0-9]{5}$"
    ConstraintDescription: "PPMC ID is a five digit number"

  UsageID:
    Description: "Usage ID a.k.a ATM ID, e.g format AA12345678"
    Type: String
    AllowedPattern: "^[A-Z]{2}[0-9]{8}$"
    ConstraintDescription: "Usage ID should be in the format AA12345678 with only upper case letters and numbers"

  TOC:
    Description: "Technology Oversight Committee. e.g ETOC"
    Type: String
    AllowedPattern: "^[A-Z-]*$"
    ConstraintDescription: "Technology Oversight Committee. e.g ETOC"

  BudgetLimit:
    Default: '9999'
    Description: "Upto 5 digit number"
    Type: String
    AllowedPattern: "^[0-9]{2,5}$"
    ConstraintDescription: "Only numbers allowed upto 5 digits"

  AlertThreshold1:
    Description: "Select an option to get alerts when Threshold is reached(Example:50%)"
    Default: '50'
    AllowedValues:
      - '50'
      - '75'
      - '95'
      - '100'
    Type: String

  AlertThreshold2:
    Description: "Select an option to get alerts when Threshold is reached(Example:75%)"
    Default: '75'
    AllowedValues:
      - '50'
      - '75'
      - '95'
      - '100'
      - 'NA'
    Type: String

  AlertThreshold3:
    Description: "Select an option to get alerts when Threshold is reached(Example:100%)"
    Default: '100'
    AllowedValues:
      - '50'
      - '75'
      - '95'
      - '100'
      - 'NA'
    Type: String

  NotificationEmail:
    Description: "Only emails within capgroup.com domain"
    Default : "na@capgroup.com"
    Type: String
    AllowedPattern: "^[a-z][-_.,a-z0-9]*@c{1}a{1}p{1}g{1}r{1}o{1}u{1}p{1}.c{1}o{1}m{1}$"
    ConstraintDescription: "Must provide a valid capgroup email distribution"

Resources:

  TriggerLambda:
    Type: "Custom::TriggerLambda"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: arn:aws:sns:us-east-1:848721808596:SCAccountBuilderTopic
      organizationUnitName: "CGUSER"
      accountName: !Sub
        - "AWS-${RI}-DEVELOPER"
        - RI: !Ref RequestorInitials
      accountType: "unmanaged"
      remediationGroup: "other"
      environmentType: "DEV"
      qaDataType: "na"
      vpcCIDRBlocke1: !Ref VPCCIDRBlockEast1
      costCenter: !Ref CostCenter
      ppmcID: !Ref PPMCId
      usageID: !Ref UsageID
      toc: !Ref TOC
      shutDownPeriod: "na"
      expiryDate: "99-00-9999"
      poc: !Ref RequestorInitials
      budgetName: !Sub
        - "BUDGET-${RI}-DEV"
        - RI: !Ref RequestorInitials
      notificationEmail: !Ref NotificationEmail
      alertThreshold1: !Ref AlertThreshold1
      alertThreshold2: !Ref AlertThreshold2
      alertThreshold3: !Ref AlertThreshold3
      budgetLimit: !Ref BudgetLimit

