AWSTemplateFormatVersion: 2010-09-09
Description: Account Builder Template.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Parameters for the newly created account
        Parameters:
          - AccountName
          - AccountType
          - EnvironmentType
          - QADataType
          - OrganizationUnit
      - Label:
          default: Network Parameters for the newly created account
        Parameters:
          - VPCCIDRBlockEast1
          - VPCCIDRBlockWest1
      - Label:
          default: Tags to be applied at the account level
        Parameters:
          - POC
          - CostCenter
          - PPMCId
          - UsageID
          - RemediationGroup
         
Parameters:

  AccountName:
    Description: "Name of the new AWS Account Name, upper case letters, hyphens and numbers"
    Default : "ACCOUNT-NAME-DEV"
    Type: String
    AllowedPattern: "^[A-Z][-A-Z0-9]*$"
    ConstraintDescription: "Account name can only contain upper case letters, hyphens and numbers"

  AccountType:
    Description: "Type of account if its managed vs unmanaged"
    Default : managed
    Type: String
    AllowedValues:
      - managed
      - unmanaged

  RemediationGroup:
    Description: "Remediation group to send tickets for unmanaged accounts through ServiceNow"
    Default : other
    Type: String

  OrganizationUnit:
    Description: "Name of the parent organization unit to which the account should be moved to."
    Default : "CGUSER"
    Type: String
    AllowedValues:
      - FTDEV
      - LAB
      - CGUSER

  EnvironmentType:
    Description: "Type of environment for which the account is being created"
    Default : "SBX"
    Type: String
    AllowedValues:
      - NA
      - Foundation
      - SBX
      - DEV
      - QA
      - PRD

  QADataType:
    Description: "Applicable only if its a QA account, sensitive vs non-sensitive otherwise choose na"
    Default : "na"
    Type: String
    AllowedValues:
      - na
      - non-sensitive
      - sensitive

  VPCCIDRBlockEast1:
    Description: "VPC CIDR block for east-1 region, e.g 10.220.6.0/25"
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: "VPC CIDR Block for US East1 region (e.g 10.220.6.0/25)"
    Type: String

  VPCCIDRBlockWest1:
    Description: "VPC CIDR block for west-1 region, e.g 10.220.7.0/25"
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: "VPC CIDR Block for US West1 region (e.g 10.220.6.0/25)"
    Type: String

  POC:
    Description: "Initials of individual who will be the point of contact for this account. Default will be NA for managed accounts"
    Default : "NA"
    Type: String
    AllowedPattern: "^[A-Z]*$"

  CostCenter:
    Description: "Cost Center, please enter valid 6 digit number"
    Type: String
    AllowedPattern: "^[0-9]{6}$"
    ConstraintDescription: "Cost Center is a six digit number"

  PPMCId:
    Description: "PPMC ID, please enter a valid 5 digit number"
    Type: String
    AllowedPattern: "^[0-9]{5}$"
    ConstraintDescription: "PPMC ID is a five digit number"

  UsageID:
    Description: "Usage ID a.k.a ATM ID, e.g format AA12345678"
    Type: String
    AllowedPattern: "^[A-Z]{2}[0-9]{8}$"
    ConstraintDescription: "Usage ID should be in the format AA12345678 with only upper case letters and numbers"

Resources:

  TriggerLambda:
    Type: "Custom::TriggerLambda"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: arn:aws:sns:us-east-1:848721808596:SCAccountBuilderTopic
      organizationUnitName: !Ref OrganizationUnit
      accountName: !Ref AccountName
      accountType: !Ref AccountType
      remediationGroup: !Ref RemediationGroup
      environmentType: !Ref EnvironmentType
      qaDataType: !Ref QADataType
      vpcCIDRBlocke1: !Ref VPCCIDRBlockEast1
      vpcCIDRBlockw1: !Ref VPCCIDRBlockWest1
      costCenter: !Ref CostCenter
      ppmcID: !Ref PPMCId
      usageID: !Ref UsageID
      poc: !Ref POC
