AWSTemplateFormatVersion: 2010-09-09
Description: Account Builder Lifecycle product.
Parameters:
  PortfolioProvider:
    Type: String
    Description: Owner and Distributor Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for account-builder products.
  PortfolioId:
    Type: String
    Description: The ServiceCatalog portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  ServiceCatalogGovernanceTopic:
    Type: String
    Description: ARN of SNS Topic that receives notifications when a product is created.
Resources:
  SCABOnScheduleLifecycleProduct:
    Type: 'AWS::ServiceCatalog::CloudFormationProduct'
    Properties:
      Name: Account Builder for Lifecycle Accounts
      Description: >-
        Please make sure the "Product Name" is unique for every environment you are requesting to create an AWS account for the application. 
        For example if "Application Name" is "VOLTA" , please identify the product names as follows 
        Environment - DEV, Product Name - "VOLTA-DEV" 
        Environment - QA, Product Name - "VOLTA-QA" 
        Environment - PRD, Product Name - "VOLTA-PRD"
      Owner: !Ref PortfolioProvider
      Distributor: !Ref PortfolioProvider
      SupportDescription: Cloud Support Team
      SupportEmail: PDS_-_Platform_Design_services@capgroup.com
      AcceptLanguage: en
      SupportUrl: 'http://capitalgroup.service-now.com'
      ProvisioningArtifactParameters:
        - Description: baseline version
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}servicecatalog/account-builder/scheduler/approval-workflow/CFABLifeCycle.yml'
          Name: v1.0
  AssociateABOnScheduleLifecycle:
    Type: 'AWS::ServiceCatalog::PortfolioProductAssociation'
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref SCABOnScheduleLifecycleProduct
  ConstraintAccountBuilder:
    Type: 'AWS::ServiceCatalog::LaunchRoleConstraint'
    DependsOn: AssociateABOnScheduleLifecycle
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref SCABOnScheduleLifecycleProduct
      RoleArn: !Ref LaunchConstraintARN
      Description: !Ref LaunchConstraintARN

  AccountBuilderCreatedLaunchNotification:
    Type: "AWS::ServiceCatalog::LaunchNotificationConstraint"
    Properties:
      Description: "Publishes notifications when new account creation is launched."
      NotificationArns: 
        - !Ref ServiceCatalogGovernanceTopic
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref SCABOnScheduleLifecycleProduct
    DependsOn: AssociateABOnScheduleLifecycle
Outputs:
  ProductId:
    Value: !Ref SCABOnScheduleLifecycleProduct