# populate and create configuration file from template
- name: check if s3 policy already exist    
  stat: 
    path: "s3_policy.json"
  register: file_stats


- name: create ocp s3 policy
  template:
    dest: "{{ role_path }}/files/s3_policy.json"
    src: "{{ role_path }}/templates/ocp-s3-policy-template.j2"
    mode: "u=rw,g=r,o=r"
    backup: yes
  when: file_stats.stat.exists == false

- debug:
    msg: "INFO: ocp s3 policy already exist.  Skipping..."
  when: file_stats.stat.exists == true