---

- name: Create new IAM users with API keys
  iam:
    iam_type: user
    name: "{{ item.value.name }}"
    state: present
    access_key_state: create
  with_dict: "{{ openshift_iam_user }}"
  register: user_output

- name: Output of creating iam_user
  debug:
    msg: "{{ user_output }}"

- name: Output of 1st credentials
  debug:
    msg: "{{ user_output.results[0].user_meta.access_keys }}"
  register: credentials_output

- name: Output of 2nd credentials
  debug:
    msg: "{{ user_output.results[1].user_meta.access_keys }}"
  register: credentials2_output

- name: Save user credentials
  copy:
    content="{{ credentials_output | to_nice_json }}"
    dest="./{{ openshift_aws_clusterid }}_user_credentials.txt" mode=0600

- name: Save user credentials
  copy:
    content="{{ credentials2_output | to_nice_json }}"
    dest="./{{ openshift_aws_clusterid }}_user_credentials2.txt" mode=0600
