---

#####
# these tasks are to resolve an issue with AWS us-east-1 region with long hostnames
# to be run using ocp_post_playbook.yml playbook   
#####

- name: fetch hostname of remote host
  command: curl http://169.254.169.254/latest/meta-data/hostname
  register: myhostname

- debug:
    msg: "{{ myhostname.stdout }}"

- name: set the hostname 
  command: hostnamectl set-hostname --static {{ myhostname.stdout }}

- name: enable hostname preservation in cloud config   
  lineinfile:
    path: /etc/cloud/cloud.cfg
    line: "preserve_hostname: true"
    backup: yes

- name: create cfg to preserve hostname  
  copy:
    content: "preserve_hostname: true"
    dest: /etc/cloud/cloud.cfg.d/99_hostname.cfg
    owner: root
    group: root
    mode: 0644
    force: no    

