AWSTemplateFormatVersion: 2010-09-09
Description: Wrapper Template for Auto Tag DCIP Account
Parameters:
  AccountCostCenter:
    Default: 524086  
    Type: String
  AccountPPMCId:
    Default: 79348  
    Type: String
  AccountTOC:
    Default: IG-TOC
    Type: String
  AccountUsageId:
    Default: AA00002881
    Type: String
  AccountExpDate:
    Default: 99-00-9999  
    Type: String
  AccountEnvType:
    Default: dev
    AllowedValues:
      - ftdev
      - lab
      - dev
      - qa
      - prod
    Type: String
  AccountSDPeriod:
    Default: na  
    Type: String
Resources:
  AutoTagResources:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AccountCostCenter: !Ref AccountCostCenter
        AccountPPMCId: !Ref AccountPPMCId
        AccountTOC: !Ref AccountTOC
        AccountUsageId: !Ref AccountUsageId
        AccountExpDate: !Ref AccountExpDate
        AccountEnvType: !Ref AccountEnvType
        AccountSDPeriod: !Ref AccountSDPeriod
      Tags:
        - Key: cost-center
          Value: 524154
        - Key: ppmc-id
          Value: 69058
        - Key: usage-id
          Value: BB00000008
        - Key: toc 
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: prod
        - Key: sd-period
          Value: na
        - Key: category
          Value: governance                                                  
      TemplateURL: https://organization-cftemplates.s3-us-west-1.amazonaws.com/CFAutoTagAccount.yml