AWSTemplateFormatVersion: 2010-09-09
Description: KMS Keys Creation Template.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Parameters for creation of KMS Keys within an AWS account
        Parameters:
          - environmenttype
          - accountname
          - accountid
          - kmsresources
          - kmsregions

Parameters:
  accountid:
    Description: "Account ID"
    Type: String
    MinLength: 12
    MaxLength: 12
    ConstraintDescription: "Must provide a valid 12 digit account id"

  accountname:
    Description: "Name of the new AWS Account Name"
    Default : "ACCOUNT-NAME-DEV"
    Type: String
    AllowedPattern: "^[A-Z][-A-Z0-9]*$"
    ConstraintDescription: "Account name can only contain upper case letters, hyphens and numbers"

  environmenttype:
    Description: "Type of environment for which the account is being created"
    Default : "SBX"
    Type: String
    AllowedValues:
      - Foundation
      - FTDev
      - Lab
      - SBX
      - DEV
      - QA
      - PRD

  kmsresources:
    Description: "Key resources for which keys have to provisioned"
    Default : "s3"
    Type: String
    AllowedValues:
      - s3
      - rds
      - vol
      - s3,rds
      - s3,vol
      - rds,vol
      - s3,rds,vol

  kmsregions:
    Description: "Account regions where keys have to be provisioned"
    Default : "us-east-1"
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-east-1,us-east-2
      - us-west-1,us-west-2
      - us-east-1,us-west-1
      - us-east-2,us-west-2
      - us-west-1,us-east-1,us-east-2
      - us-west-1,us-east-1,us-west-2,us-east-2

Resources:

  TriggerLambda:
    Type: "Custom::TriggerLambda"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:848721808596:function:LFCreateKMSKeysForAccount
      environment_type: !Ref environmenttype
      account_name: !Ref accountname
      account_id: !Ref accountid
      kms_resources: !Ref kmsresources
      kms_regions: !Ref kmsregions