AWSTemplateFormatVersion: 2010-09-09
Description: Wrapper Template for CFServiceCatalogKMSOnboard
Parameters:
  sourcebucket:
    Description: "Source bucket where lambda function zip file is stored."
    Default : "organization-repo"
    Type: String
  KMSServiceAccountCreds:
    Default: KMSServiceAccountCreds
    Description: Secret name where KMS Okta credentials are stored
    Type: String
  KMSOktaURL:
    Default: https://capgroup.okta.com/oauth2/aus1gdjnsxvx1kTEb1d8/v1/token?grant_type=client_credentials
    Description: Okta url to generate token for KMS authentication
    Type: String
  KMSAPIURL:
    Default: https://keys.capgroup.com:8443/hsm
    Description: API url to encrypt generated KMS CMK
    Type: String
  SecretsManagerRegion:
    Default: us-east-1
    Type: String
Resources:
  CFServiceCatalogKMSOnboard:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        sourcebucket: !Ref sourcebucket
        SecretsManagerRegion: !Ref SecretsManagerRegion
        KMSServiceAccountCreds: !Ref KMSServiceAccountCreds
        KMSOktaURL: !Ref KMSOktaURL
        KMSAPIURL: !Ref KMSAPIURL
      Tags:
        - Key: cost-center
          Value: 524154
        - Key: ppmc-id
          Value: 69058
        - Key: usage-id
          Value: BB00000008
        - Key: toc 
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: ftdev
        - Key: sd-period
          Value: na   
        - Key: category
          Value: governance                                               
      TemplateURL: https://organization-repo.s3.amazonaws.com/servicecatalog/CFServiceCatalogKMSOnboard.yml