AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'encrypt-volume

  Sample SAM Template for encrypt-volume

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: EncryptUnencryptedVolumes
    Description: Encrypt volumes within an AWS account which are unencrypted
    SemanticVersion: 0.0.7
    Author: PlatformDesignTeam
Resources:
  EncryptUnencryptedVolumes:
    Type: AWS::Lambda::Function
    Properties:
      Handler: EncryptUnencryptedVolumes.lambda_handler
      Role:
        Fn::GetAtt:
        - EncryptUnencryptedVolumesRole
        - Arn
      Runtime: python3.8
      Timeout: 300
      Code:
        S3Bucket: organization-repo
        S3Key: 1dff33ea9bc416d25e099aad10946126
  EncryptUnencryptedVolumesLG:
    Type: AWS::Logs::LogGroup
    DependsOn: EncryptUnencryptedVolumes
    Properties:
      LogGroupName:
        Fn::Join:
        - ''
        - - /aws/lambda/
          - Ref: EncryptUnencryptedVolumes
      RetentionInDays: 14
  EncryptUnencryptedVolumesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EncryptUnencryptedVolumesRole
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: EncryptUnencryptedVolumesPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: logs:CreateLogGroup
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - arn:aws:logs:*:*:log-group:/aws/lambda/*:*
          - Effect: Allow
            Action:
            - ec2:DescribeTags
            - ec2:GetEbsDefaultKmsKeyId
            Resource: '*'
          - Effect: Allow
            Action: ec2:CreateTags
            Resource:
            - arn:aws:ec2:*::snapshot/*
            - arn:aws:ec2:*:*:volume/*
          - Effect: Allow
            Action:
            - kms:Decrypt
            - kms:GenerateDataKeyWithoutPlaintext
            - kms:GenerateDataKeyPairWithoutPlaintext
            - kms:GenerateDataKeyPair
            - kms:ReEncryptFrom
            - kms:Encrypt
            - kms:GenerateDataKey
            - kms:ReEncryptTo
            - kms:DescribeKey
            Resource:
            - arn:aws:kms:*:*:key/*
          - Effect: Allow
            Action:
            - sts:AssumeRole
            Resource:
            - arn:aws:iam::848721808596:role/OrganizationsReadAccessRole
          - Effect: Allow
            Action:
            - ec2:CreateVolume
            - ec2:CreateSnapshot
            Resource:
            - arn:aws:ec2:*::snapshot/*
            - arn:aws:ec2:*:*:volume/*
Outputs:
  EncryptUnencryptedVolumes:
    Description: Convert unencrypted to encrypted volumes within an account
    Value:
      Fn::GetAtt:
      - EncryptUnencryptedVolumes
      - Arn
  EncryptUnencryptedVolumesRole:
    Description: Function role to convert unencrypted to encrypted volumes within
      an account
    Value:
      Fn::GetAtt:
      - EncryptUnencryptedVolumesRole
      - Arn
