AWSTemplateFormatVersion: 2010-09-09
Description: Event rule for log group creation
Parameters:
  EventBusAccountID:
    Default: 848721808596  
    Type: String
Resources:
  CWLogEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: >-
        Send log group creation event to central event bus for subscription filter setup
      EventPattern:
        source: 
          - aws.logs
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - logs.amazonaws.com
          eventName:
            - CreateLogGroup
      Name: Member-CWLogGroup-Filter-Creation
      State: DISABLED
      Targets:
        -
          Arn: !Sub 'arn:aws:events:${AWS::Region}:${EventBusAccountID}:event-bus/loggroupfilter'
          RoleArn:
            Fn::GetAtt: 
              - "CWLogEventRole"
              - "Arn"
          Id: "LogGroupEventBus"
  CWLogEventRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Tags:
        -
           Key: cost-center
           Value: 524154
        -
           Key: ppmc-id
           Value: 69058
        -
           Key: toc
           Value: ETOC
        -
           Key: usage-id
           Value: BB00000008
        -
           Key: exp-date
           Value: 99-00-9999
        -
           Key: env-type
           Value: prd
        -
           Key: sd-period
           Value: na
        -
           Key: category
           Value: governance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: CWLogEventBusPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: Stmt1458923121000
                Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - !Sub 'arn:aws:events:${AWS::Region}:${EventBusAccountID}:event-bus/loggroupfilter'
Outputs: {}