AWSTemplateFormatVersion: 2010-09-09
Description: KMS Keys Creation Template.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Parameters for creation of KMS Keys within an AWS account
        Parameters:
          - kmsresource
          - kmsregion

Parameters:

  kmsresource:
    Description: "Resource type for key provisioning, 'common' option for all other services outside of s3, rds, ebs and secrets manager"
    Default : "secretsmanager"
    Type: String
    AllowedValues:
      - secretsmanager
      - common

  kmsregion:
    Description: "Region where key will be provisioned"
    Default : "us-east-1"
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2

Resources:

  WaitHandle:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
  WaitCondition:
    Type: 'AWS::CloudFormation::WaitCondition'
    Properties:
      Handle:
        Ref: 'WaitHandle'
      Timeout: '14400'
  TriggerSNS:
    Type: "Custom::TriggerSNS"
    Properties:
      ServiceToken: arn:aws:sns:us-east-1:848721808596:ServiceCatalogKMSTopic
      account_id: !Ref "AWS::AccountId"
      kms_resource: !Ref kmsresource
      kms_region: !Ref kmsregion
      WaitUrl: !Ref WaitHandle