AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket within an account
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Parameters for creation of S3 bucket within an AWS account
        Parameters:
          - S3BucketName
          - S3BucketRegion
      - Label:
          default: Parameters for Prod if bucket replication across regions is required
        Parameters:
          - EnableReplicationInProd
          - DestinationRegion
      - Label:
          default: Tags to be applied to the S3 bucket
        Parameters:
          - CostCenter
          - PPMCId
          - TOC
          - UsageID
          - ExpirationDate
          - EnvironmentType
          - SDPeriod
Parameters:
  S3BucketName:
    Description: "The name of the S3 bucket, should not contain upper case letters and underscores. Should start with a letter or number."
    Type: String

  S3BucketRegion:
    Description: "Region where bucket has to be provisioned within the account"
    Default : "us-east-1"
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2

  EnableReplicationInProd:
    Description: "Is Bucket Replication required 'true' or 'false' (only if Prod)?"
    Default: na
    Type: String
    AllowedValues:
      - na
      - yes
      - no

  DestinationRegion:
    Description: "Destination region for bucket replication (different from source bucket region)"
    Default : "na"
    Type: String
    AllowedValues:
      - na
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2

  CostCenter:
    Description: "Cost Center - six digit number"
    Type: String
    AllowedPattern: "^[0-9]{6}$"
    ConstraintDescription: "Cost Center is a six digit number"

  EnvironmentType:
    Description: "Environment Type"
    Default: dev
    Type: String
    AllowedValues:
      - sbx
      - dev
      - qa
      - prd

  ExpirationDate:
    Description: "Expiration date for the resources to be provisioned within the account if applicable, in the format MM-DD-YYYY"
    Default: 99-00-9999
    Type: String
    AllowedPattern: "^[0-9]{2}-[0-9]{2}-[0-9]{4}$"
    ConstraintDescription: "Expiration date should be in the format MM-DD-YYYY"

  PPMCId:
    Description: "PPMC ID to be used - five digit number"
    Type: String
    AllowedPattern: "^[0-9]{5}$"
    ConstraintDescription: "PPMC ID is a five digit number"

  TOC:
    Description: "TOC, upper case letters with or without hyphens"
    Type: String
    AllowedPattern: "^[A-Z][-A-Z]*$"
    ConstraintDescription: "TOC can only contain upper case letters with or without hyphens"

  UsageID:
    Description: "Usage ID/ATM Id, should be in the format AA12345678 with only upper case letters and numbers"
    Type: String
    AllowedPattern: "^[A-Z]{2}[0-9]{8}$"
    ConstraintDescription: "Usage ID should be in the format AA12345678 with only upper case letters and numbers"

  SDPeriod:
    Description: "Shut Down Period, for S3 buckets it will be the default value 'na'"
    Default: 'na'
    Type: String

Resources:
  TriggerLambda:
    Type: "Custom::TriggerLambda"
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:us-east-1:${AWS::AccountId}:function:ServiceCatalog-LFCreateS3Bucket'
      accountid: !Ref "AWS::AccountId"
      bucketname: !Ref S3BucketName
      region: !Ref S3BucketRegion
      enable_replication: !Ref EnableReplicationInProd
      replication_region: !Ref DestinationRegion
      costcenter: !Ref CostCenter
      envtype: !Ref EnvironmentType
      expdate: !Ref ExpirationDate
      ppmcid: !Ref PPMCId
      toc: !Ref TOC
      usageid: !Ref UsageID
      sdperiod: !Ref SDPeriod