AWSTemplateFormatVersion: 2010-09-09
Description: Wrapper Template for CFServiceCatalogVPCCreation
Parameters:
  sourceBucket:
    Default: organization-repo  
    Type: String
  NetworkAnsibleTowerURL:
    Default: https://tower.cguser.capgroup.com/api/v2/job_templates/1049/launch/
    Type: String
  SecretsManagerRegion:
    Default: us-east-1
    Type: String
  NetworkServiceAccountCreds:
    Default: IAMAccessCredentials
    Type: String
Resources:
  CFServiceCatalogVPCCreation:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        sourceBucket: !Ref sourceBucket
        NetworkAnsibleTowerURL: !Ref NetworkAnsibleTowerURL
        SecretsManagerRegion: !Ref SecretsManagerRegion
        NetworkServiceAccountCreds: !Ref NetworkServiceAccountCreds
      Tags:
        - Key: cost-center
          Value: 524154
        - Key: ppmc-id
          Value: 69058
        - Key: usage-id
          Value: BB00000008
        - Key: toc 
          Value: ETOC
        - Key: exp-date
          Value: 99-00-9999
        - Key: env-type
          Value: ftdev
        - Key: sd-period
          Value: na   
        - Key: category
          Value: governance                                               
      TemplateURL: https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFServiceCatalogVPCCreation.yml