Description: "This CloudFormation template sets up hub portfolio, adds the product specified and shares the portfolio with a spoke account"
Parameters:
  S3CFNPath:
    Description: Complete s3 path of S3 Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateS3BucketSelfService.yml"
  KMSCFNPath:
    Description: Complete s3 path of KMS Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateKMSKeySelfService.yml"
  BUDGETCFNPath:
    Description: Complete s3 path of Budget Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateBudgetSelfService.yml"
Resources:
  HubTestPortfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      AcceptLanguage: "en"
      Description: "Application Hub Test Portfolio."
      DisplayName: "Application Hub Test Portfolio"
      ProviderName: "CCOE"
  KMSProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "KMS Product to provision key within an account"
      Distributor: "CCOE"
      Name: "KMS"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an KMS product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of KMS creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref KMSCFNPath
  KMSPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubTestPortfolio
      ProductId: !Ref KMSProduct
  BudgetProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "Budget Product to setup budgets within an account"
      Distributor: "CCOE"
      Name: "Budget"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an Budget product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of Budget creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref BUDGETCFNPath
  BudgetPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubTestPortfolio
      ProductId: !Ref BudgetProduct
  S3Product:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "S3 Product with replication option for production environment"
      Distributor: "CCOE"
      Name: "S3 bucket"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an S3 product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of S3 bucket creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref S3CFNPath
  S3PortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubTestPortfolio
      ProductId: !Ref S3Product
Outputs:
  PortfolioID:
    Value: !Ref HubTestPortfolio 
  S3ProductID:
    Value: !Ref S3Product 
  KMSProductID:
    Value: !Ref KMSProduct
  BudgetProductID:
    Value: !Ref BudgetProduct