AWSTemplateFormatVersion: 2010-09-09
Description: "This CloudFormation template sets up hub portfolio, adds the product specified and shares the portfolio with a spoke account"
Parameters:
  S3CFNPath:
    Description: Complete s3 path of S3 Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFProvisionS3BucketSelfService.yml"
  KMSCFNPath:
    Description: Complete s3 path of KMS Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateKMSSelfService.yml"
  BudgetCFNPath:
    Description: Complete s3 path of Budget Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateBudgetSelfService.yml"
  VPCCFNPath:
    Description: Complete s3 path of VPCCreate Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateVPCsSelfService.yml"
  VPCENDPOINTCFNPath:
    Description: Complete s3 path of VPC Endpoint creation Product CloudFormation template.
    Type: String
    Default: "https://organization-repo.s3.amazonaws.com/servicecatalog/appl-portfolio/CFCreateVPCEndpointSelfService.yml"
Resources:
  HubPortfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      AcceptLanguage: "en"
      Description: "Application Hub Portfolio."
      DisplayName: "Application Hub Portfolio"
      ProviderName: "CCOE"
  KMSProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "KMS Product to provision key within an account"
      Distributor: "CCOE"
      Name: "KMS"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an KMS product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of KMS creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref KMSCFNPath
  KMSPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubPortfolio
      ProductId: !Ref KMSProduct
  BudgetProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "Budget Product to provision key within an account"
      Distributor: "CCOE"
      Name: "Budget"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an Budget product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of Budget creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref BudgetCFNPath
  BudgetPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubPortfolio
      ProductId: !Ref BudgetProduct
  S3Product:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "S3 Product with replication option for production environment"
      Distributor: "CCOE"
      Name: "S3 bucket"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an S3 product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of S3 bucket creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref S3CFNPath
  S3PortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubPortfolio
      ProductId: !Ref S3Product
  VPCCreateProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "VPCCreate Product to provision VPC within an account"
      Distributor: "CCOE"
      Name: "VPC Create"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an VPC Create product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of VPC creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref VPCCFNPath
  VPCPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubPortfolio
      ProductId: !Ref VPCCreateProduct
  VPCEndpointCreateProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "en"
      Description: "VPC Endpoint Product to provision VPC Endpoints(S3,Logs,ECR-DKR,ECR-API) within an account"
      Distributor: "CCOE"
      Name: "ECS VPC Endpoints"
      Owner: "CCOE"
      SupportEmail: "PDS_-_Platform_Design_services@capgroup.com"
      SupportUrl: "https://capitalgroup.service-now.com"
      SupportDescription: "This is an ECS VPC Endpoint Create product that CCOE team needs to customize and support."
      ProvisioningArtifactParameters:
        -
          Description: "Version 1 of VPC creation product"
          Name: "Version - 1.0"
          Info:
            LoadTemplateFromURL : !Ref VPCENDPOINTCFNPath
  VPCEndpointPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "en"
      PortfolioId: !Ref HubPortfolio
      ProductId: !Ref VPCEndpointCreateProduct    
Outputs:
  PortfolioID:
    Value: !Ref HubPortfolio 
  S3ProductID:
    Value: !Ref S3Product 
  KMSProductID:
    Value: !Ref KMSProduct
  VPCCreateProductID:
    Value: !Ref VPCCreateProduct
  VPCEndpointCreateProductID:
    Value: !Ref VPCEndpointCreateProduct