---

#
# tasks to create database ec2 instances for ESI 
#

- name: create the database instances 
  ec2:
    region: "{{ esi_aws_region }}"
    key_name: "{{ esi_aws_ssh_key_name }}"
    instance_type: "{{ esi_aws_ec2_database_instance_type }}"
    vpc_subnet_id: "{{ item.subnet }}"
    image: "{{ esi_aws_rootenc_ami }}"
    termination_protection: "{{ esi_aws_ec2_termination_protection }}"
    user_data: "{{ esi_aws_ec2_database_user_data }}"
    wait: yes
    count: "{{ item.count }}"
    instance_tags: "{{ esi_aws_resource_tags }}"
  register: database_hosts
  with_items: "{{ esi_aws_admin_subnet }}" 

- debug:
    msg: "{{ database_hosts }}"

- name: fetch newly created instance
  ec2_instance_facts:
    region: "{{ esi_aws_region }}"
    filters:
      "tag:app-type": "{{ esi_aws_resource_type }}"      
      instance-state-name: running
      subnet-id: "{{ item.subnet }}"
      availability-zone: "{{ item.az }}"
      instance-id: "{{ database_hosts.results[0].instance_ids }}"
  register: instancesout
  with_items: "{{ esi_aws_admin_subnet }}"  
  retries: 20
  delay: 3
  until: instancesout|length > 0

- debug:
    msg: "{{ instancesout.results[0].instances[0].instance_id }}"

# create data volume and attach to instance
- name: create new volume and attach to instance
  ec2_vol:
    instance: "{{ instancesout.results[0].instances[0].instance_id }}"
    encrypted: true
    tags: "{{ esi_aws_resource_tags }}"
    kms_key_id: "{{ item.value.kms_key_id }}"
    delete_on_termination: yes
    volume_size: "{{ item.value.volume_size }}"
    volume_type: "{{ item.value.volume_type }}"
    iops: "{{ item.value.volume_iops }}"
    state: present
    device_name: "{{ item.value.device_name }}"
    region: "{{ esi_aws_region }}"
  with_dict: "{{ esi_aws_database_instance_data_volume }}"

# the following tasks tags all related resources attached to the master instances
- name: tag eth0 network interfaces
  ec2_tag:
    region: "{{ esi_aws_region}}"
    resource: "{{ item.instances[0].network_interfaces[0].network_interface_id }}"
    state: present
    tags: "{{ esi_aws_resource_tags }}"
  with_items: "{{ instancesout.results }}"

- name: tag all attached root volume
  ec2_tag:
    region: "{{ esi_aws_region}}"
    resource: "{{ item.instances[0].block_device_mappings[0].ebs.volume_id }}"
    state: present
    tags: "{{ esi_aws_resource_tags }}"
  with_items: "{{ instancesout.results }}"

      
