AWSTemplateFormatVersion: 2010-09-09
Description: Deploy CloudWatch Event rule(s) for various resource creation events in Member accounts
Parameters:
  EventBusAccountID:
    Default: 848721808596
    Type: String
Resources:
  Route53EventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Direct all Route53 creation events to an event bus in Master account
      EventPattern:
        source:
        - aws.route53
        detail-type:
        - AWS API Call via CloudTrail
        detail:
          eventSource:
          - route53.amazonaws.com
          eventName:
          - CreateHostedZone
          - CreateHealthCheck
          - CreateQueryLoggingConfig
          - CreateReusableDelegationSet
          - CreateTrafficPolicy
          - CreateTrafficPolicyInstance
          - CreateTrafficPolicyVersion
          - CreateVPCAssociationAuthorization
          - CreateResolverEndpoint
          - CreateResolverRule
      Name: AutoTag-Route53-Event
      State: ENABLED
      Targets:
        -
          Arn: 
            Fn::Sub:
             'arn:aws:events:${AWS::Region}:${EventBusAccountID}:event-bus/tagging'
          RoleArn:
            Fn::GetAtt:
              - "Route53EventRole"
              - "Arn"
          Id: "AutotaggingEventBus"
  Route53EventRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Tags:
        -
           Key: cost-center
           Value: 524154
        -
           Key: ppmc-id
           Value: 69058
        -
           Key: toc
           Value: ETOC
        -
           Key: usage-id
           Value: BB00000008
        -
           Key: exp-date
           Value: 99-00-9999
        -
           Key: env-type
           Value: prd
        -
           Key: sd-period
           Value: na
        -
           Key: category
           Value: governance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: Route53EventBusPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  Fn::Sub:
                    'arn:aws:events:${AWS::Region}:${EventBusAccountID}:event-bus/tagging'
Outputs: {}