---

##### 
# A OCP playbook to re-enbale the required yum repositories on a host or set of hosts
# 
# Instruction:  
#    To run:
#      1. Run playbook: ansible-playbook -i <inventory file> -e "host_name=<host label>" ocp_reenable_repos.yml
#
# Example:  ansible-playbook -i ocp-nadqa-west1.cfg -e "host_name=infra[0]" day2_ocp_reenable_repos.yml
# 
#
#  LastUpdated: 2018-10-20
#  UpdatedBy: Cuong Tong ( cuot@capgroup.com )
#

- hosts: "{{ host_name }}"
  gather_facts: no

  tasks:
  - name: retrieve Openshift version
    command: oc version
    register: version_output

  - debug: var=version_output

  - block:
    - name: Disable all repos v3.7
      command: yum-config-manager --disable \*
    - name: Enable required repos v3.7  
      command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"
    ignore_errors: true
    when: ("v3.7" in version_output.stdout)

  - block:
    - name: Disable all repos v3.9
      command: yum-config-manager --disable \*
    - name: Enable required repos v3.9  
      command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
    ignore_errors: true
    when: ("v3.9" in version_output.stdout) 

        