---

- hosts: localhost
  connection: local
  gather_facts: no
 
##########################################################################################################
#
# Playbook for provisioning of 3 node Openshift Container Platform in AWS 
# Set control flags to create/provision the following:
#   - create key pair for ssh 
#   - create an encrypted AMI image to use
#   - provision security groups
#   - provision control/bastion, master, app and infra hosts
#   - create elbs
#   - create the inventory configuration file
#   - provision IAM user and policies
#   - provision S3 bucket and policies
#
# Instruction:  
#    To run:
#      1: Run playbook:  ansible-playbook -e "env_var_file=<env specific vars>" day2_ocp_modify_elb.yml 
#
# Example:  ansible-playbook -e "env_var_file=int_dev_us_east_1.yml" day2_ocp_modify_elb.yml 
#
# extra-vars options 
#  --------------------------------------------------------------------------------------------------------------------
#  |  variable name           |       value                 |    require or optionanl   |     comments
#  --------------------------------------------------------------------------------------------------------------------
#  | env_var_file             | env specif var file         |    require                | located under roles/openshift/vars/
#  ---------------------------------------------------------------------------------------------------------------------
#
#  LastUpdated: 2018-10-31
#  UpdatedBy: Philip Phan ( phlp@capgroup.com )
#

  vars:
    # define env specific var 
    openshift_aws_env_var_file: "{{ env_var_file }}"
    # flags to enable / disable tasks  
    #openshift_aws_create_elb: False


  tasks:
  - fail:
      msg: "{{ item }} needs to be defined"
    when: item not in vars
    with_items:
    - env_var_file
      
  - name: include env file to work around ansible 2.4 issue
    include_vars: roles/openshift/vars/{{ env_var_file }}

  # create elbs
  - name: create elb 
    include_role:
      name: openshift
      #vars_from: "{{ openshift_aws_env_var_file }}"
      tasks_from: day2_modify_elb.yml
      #tasks_from: day2_output_elb.yml
    vars:
      openshift_aws_resource_type: "{{ aws_loadbalancer_type }}"
    #when: openshift_aws_create_elb | default(True) | bool

