---
##### 
# Update Portworx and Stork versions
#
# Instruction:
#  Openshift 3.11 SNX1/SNX2 Prod clusters need to do Portworx backup on application data.
#  The pre-req is to have Portworx 2.6 and Stork 2.4.4 
#  
#  This playbook upgrades Portworx and Stork to the input versions on all host in SNX1/SNX2.
#  
#  To run:
#    1. ansible-playbook -i <inventory file> -e "portworx_version=<portworx version>" -e "stork_verison=<stork version>" day2_ocp_portworx_stork_upgrade.yml 
#  
#  Example: ansible-playbook -i /home/cpzinfbb00000085s002/ocp-provisioning/ocp-prod.cfg -e "portworx_version=2.6" -e "stork_version=2.4.4" day2_ocp_portworx_stork_upgrade.yml
# 
#  LastUpdated: 2020-09-08
#  UpdatedBy: Ip Sam ( coniws@capgroup.com )
#
- name: "Update Portworx and Stork versions"
  connection: local
  gather_facts: false
  hosts: localhost
  vars: 
    portworx_version: 2.6
    stork_version: 2.4.5
    ansible_python_interpreter: /usr/bin/python3
  tasks: 
    - name: "Download Portworx Shell Script"
      shell: curl -fsSL https://install.portworx.com/{{ portworx_version }}/upgrade > portworx.sh  
    - name: "Install Portworx"
      expect:
        command: bash portworx.sh
        responses:
          continue:
            - y
    - name: Get Kube version
      k8s_info:
        kind: ClusterOperator
        name: kube-apiserver
      register: kube_vers
    - name: Set kube fact
      set_fact:
        kube_version: "{{ (kube_vers.resources[0].status.versions | selectattr('name', 'search', 'kube-apiserver') | list | first).version }}" 
    - name: "Create Stork Install File"
      shell: curl -o stork.yaml -L https://install.portworx.com/2.6?kbver={{ kube_version }}&comp=stork
    - name: "Create Stork"
      k8s:
        src: stork.yaml
        apply: yes
        state: present