---
#####
#
# Playbook to create private route53 hosted zones on ocp-int-* clusters 
# 
# Instruction:  
#    To run:
#      1. Run playbook: ansible-playbook -e "resource_id=<zone_id>" day2_ocp_int_route53_hosted_zones_tags.yml 
#      2. To get the zone_id of a newly created host zone, run the day2_ocp_int_route53_hosted_zones.yml playbook in this directory
#
#  LastUpdated: 2019-08-11
#  UpdatedBy: Randy Liang (randy.liang@capgroup.com)
#
- hosts: localhost
  connection: local

  tasks:
    - name: Fail task when the output has an error
      command: oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
      register: get_cluster_name
      any_errors_fatal: true

    - name: Set cluster name fact
      set_fact:
        cluster: "{{ get_cluster_name.stdout }}"

    - name: Create cluster name tag
      command: aws2 route53 change-tags-for-resource --resource-type hostedzone --resource-id {{ resource_id }} --add-tags Key=Name,Value={{ cluster }} 
    
    - name: Create "owned" resource tag
      command: aws2 route53 change-tags-for-resource --resource-type hostedzone --resource-id {{ resource_id }} --add-tags Key=kubernetes.io/cluster/{{ cluster }},Value=owned

    - name: Verify changes to tags have been applied
      command: aws2 route53 list-tags-for-resource --resource-type hostedzone --resource-id {{ resource_id }}
      register: verify

    - debug: 
        var: verify
