---
# file: day2_ocp_prune_cron.yml
#
# To run playbook:  ansible-playbook -i <OCP inventory file> day2_ocp_prune_cron.yml
#
# The following oc commands will be cron 
# oc adm prune deployments --orphans --keep-complete=5 --keep-failed=1 --keep-younger-than=60m --confirm
# oc adm prune builds --orphans --keep-complete=5 --keep-failed=1 --keep-younger-than=60m --confirm
# oc --token=$(oc serviceaccounts get-token pruneacct) adm prune images --keep-tag-revisions=5 --keep-younger-than=60m --confirm
#
# In AWS, these prunes OCP objects stored in S3 bucket
#
# https://confluence.capgroup.com/display/CNTEN/Pruning+and+Cleanup
#
##  LastUpdated: 2018-09-10
#  UpdatedBy: Cuong Tong ( cuot@capgroup.com )
#

- hosts: masters[0]
  vars:
    prune_script: prune-artifacts.sh
    prune_serviceaccount: pruneacct
    prune_artifacts:
      builds:
        keep_complete: 5
        keep_failed: 1
        keep_younger: 60m
        cron_weekday: "0-6"
        cron_hour: 20
        cron_minute: 0
      deployments:
        keep_complete: 5
        keep_failed: 1
        keep_younger: 60m
        cron_weekday: "0-6"
        cron_hour: 20
        cron_minute: 15       
      images:
        keep_younger: 60m
        keep_tag_revisions: 5
        cron_weekday: 1
        cron_hour: 20
        cron_minute: 30

  tasks:
  - name: check for service account
    command: oc get sa {{ prune_serviceaccount }} -n default -o name
    register: oc_output
    ignore_errors: true

  - name: create pruning account
    command: oc create sa {{ prune_serviceaccount }} -n default
    when: ("Error" in oc_output.stderr)

  - name: grant perms to pruning account
    command: oc adm policy add-cluster-role-to-user system:image-pruner system:serviceaccount:default:{{ prune_serviceaccount }}
    when: ("Error" in oc_output.stderr)

  - name: install prune artifacts script
    copy:
      src: roles/openshift/files/{{ prune_script }}
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: 0755
    run_once: true

  - name: create prune crons per artifact type
    cron:
      name: prune ocp old artifacts
      job: "/usr/local/bin/{{ prune_script }} --artifact '{{ item.key }}' --keep-complete '{{ item.value.keep_complete | default('') }}'  --keep-failed '{{ item.value.keep_failed | default('') }}'  --keep-younger '{{ item.value.keep_younger | default('') }}' --keep-tag-revisions '{{ item.value.keep_tag_revisions | default('') }}'"
      user: ec2-user
      cron_file: "prune-{{ item.key }}"
      minute: "{{ item.value.cron_minute | default('') }}"
      hour: "{{ item.value.cron_hour | default('') }}"
      weekday: "{{ item.value.cron_weekday | default('') }}"
      state: present
    with_dict: "{{ prune_artifacts }}"
    run_once: true


