---
#####
#
# Playbook to renew subscription with RHSM 
#
# Instruction:
#    To run:
#      1. Run playbook: ansible-playbook -e "rhsm_user=<user> rhsm_password=<pass>" rhsm_refresh.yml
#
# LastUpdated: 2020-07-17
# UpdatedBy: Randy Liang (randy.liang@capgroup.com)
#
- hosts: localhost
  connection: local
  
  tasks: 
    - name: Register with RHSM
      redhat_subscription:
        state: "present"
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
      become: yes
      become_method: sudo
  
    - name: Pull latest subscription data from RHSM
      shell: "subscription-manager refresh"
      become: yes
      become_method: sudo      
    
    - name: Get pool id
      shell: "subscription-manager list --available --matches='*OpenShift*' | awk '/Pool ID/ {print $3}' | head -1"
      register: "pool_id_command"
      become: yes
      become_method: sudo
      
    - name: Set pool id fact
      set_fact:
        "get_pool_id": "{{ pool_id_command.stdout }}"

    - name: Attach pool id to subscription
      command: "subscription-manager attach --pool={{ get_pool_id }}"
      become: yes
      become_method: sudo      