---
#####
#
# Playbook to subscribe to RHSM 
# 
# Instruction:  
#    To run:
#      1. Run playbook: ansible-playbook rhsm_entitlements.yml --ask-vault-pass
#
#  LastUpdated: 2019-07-31
#  UpdatedBy: Randy Liang (randy.liang@capgroup.com)
#
- hosts: localhost
  connection: local
  
  tasks:
    - name: Include vars
      include_vars:
        dir: vars

    - name: Set fact
      set_fact:
        "get_offline_token": "{{ offline_token }}"

    - debug:
        msg: "offline_token = {{ get_offline_token }}"
              
    - name: Change file permissions
      file:
        path: roles/openshift/files/rhsm-access-token.sh
        mode: '0755'
      become: yes
      become_method: sudo

    - name: Source file
      shell: source roles/openshift/files/rhsm-access-token.sh {{ offline_token }}
      become: yes
      become_method: sudo
