---

- hosts: nodes
  gather_facts: yes

  tasks:
  - name: Create a backup for /etc/rsyslog.conf on remote server
    shell: mv /etc/rsyslog.conf /etc/rsyslog.conf.backup-{{ ansible_date_time.date }}

  - name: Stop rsyslog service
    systemd:
      name: rsyslog
      state: stopped

  # - name: re-install rsyslog 
  #   command: yum -y reinstall rsyslog
  #   register: yum_out

  - debug: var=yum_out

  - name: copy rsyslog.conf over
    copy:
      src: roles/splunk/templates/rsyslog.conf.new.j2
      dest: /etc/rsyslog.conf
      mode: u=rw,g=r,o=r
      backup: yes
      force: yes

  - name: restart rsyslog service
    systemd:
      name: rsyslog
      state: restarted