---

#
# ServiceNow is not able to gothrough CyberArk to check out password
# These playbook is to reset static password for ServiceNow service accounts after account creation
#
# To run on localhost: ansible-playbook -e "targe_hosts=localhost provisioning_env=<env>" service_passwd_reset.yml
# To run on all OCP cluster hosts: ansible-playbook -i <ocp_cfg_filename> -e "target_hosts=nodes provisioning_env=<env>" service_passwd_reset.yml
#
- hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no
  
  tasks:
  - name: set password
    user:
      name: dev_aws_svcnow_unix_local_svc
      password: '$6$salt8hds$5O1E5UidOu80iwGxseaQMqbuLqcgpsX0uYZ/URy0pABT61sSqcqKyVDGrMmX/lvgS4JhPKsE.weAy76vLDO9h.'
      update_password: always
    when: provisioning_env == 'dev'

  - name: set password
    user:
      name: qa_aws_svcnow_unix_local_svc
      password: '$6$salt8hds$phkcVHbGV9lH3kWQlNWrhQKNYTl/G.W/IlrUOTnWRiUNWGccjziMR3QjGX/X2ugxFiGAoi2PuMeMlinJ7/i6r.'
      update_password: always
    when: provisioning_env == 'qa' or provisioning_env == 'stg'

  - name: set password
    user:
      name: prd_aws_svcnow_unix_local_svc
      password: '$6$salt8hds$3ZJUuezk.ksNaYz8nULn2kbHQMxBpIPfJcTYH9CYjq0D3zFtPWxiGKPvQa4QDmOrdiEflobrLBNAm8q/mtNrk.'
      update_password: always
    when: provisioning_env == 'prd'
