---
  
##### 
# These playbook is meant to execute various misc tasks
# 
# Enable flags to create/provision the following:
# - generates private key and csr  
#
#  LastUpdated: 2018-07-25
#  UpdatedBy: Cuong Tong ( cuot@capgroup.com )
#

- hosts: localhost
  tasks:
  - fail:
      msg: "{{ item }} needs to be defined"
    when: item not in vars
    with_items:
    - fqdn

  # certificate generation
  - name: generate certificate CSR
    import_role:
      name: utils
      tasks_from: certificate_tools.yml
    vars:
      # ex. certificate common name: ocp-console.prod-nad-usw1-aws.csp.capgroup.com
      cert_common_name: "{{ fqdn }}"
      # 2k private key
      cert_rsa_key_size: "2048"
      # 4k private key
      #cert_rsa_key_size: "4096"
      # if using python-pyOpenSSL; if not, leave as False
      cert_pyopenssl_available: False

