AWSTemplateFormatVersion: 2010-09-09
Description: Baseline CloudMapper Access setup for all accounts

Parameters:
  AdministratorAccountId:
    Type: String
    Default: 848721808596
    Description: AWS Account Id of the administrator account (the account in which StackSets will be created).
    MaxLength: 12
    MinLength: 12

Resources:
  CloudMapperRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudMapperRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess