Resources:
  SMEndpointConfigurationKMSKeyConfigured:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: SageMakerEndpointConfigurationKMSKeyConfigured
      Description: >- 
        Checks whether AWS Key Management Service (KMS) key is configured for an Amazon SageMaker endpoint configuration. 
        The rule is NON_COMPLIANT if KmsKeyId is not specified for the Amazon SageMaker endpoint configuration.
      Scope:
        ComplianceResourceTypes:
        - "AWS::SageMaker::EndpointConfig"
      Source:
        Owner: AWS
        SourceIdentifier: SAGEMAKER_ENDPOINT_CONFIGURATION_KMS_KEY_CONFIGURED
      MaximumExecutionFrequency: Six_Hours
  SMNotebookNoDirectInternetAccess: 
    Type: "AWS::Config::ConfigRule"
    Properties: 
      ConfigRuleName: SageMakerNotebookNoDirectInternetAccess
      Description: >-
        Checks whether direct internet access is disabled for an Amazon SageMaker notebook instance. 
        The rule is NON_COMPLIANT if Amazon SageMaker notebook instances are internet-enabled.      
      Scope: 
        ComplianceResourceTypes: 
        - "AWS::SageMaker::NotebookInstance"
      Source: 
        Owner: AWS
        SourceIdentifier: SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS
      MaximumExecutionFrequency: Six_Hours
  SMNotebookInstanceKMSKeyConfigured: 
    Type: "AWS::Config::ConfigRule"
    Properties: 
      ConfigRuleName: SageMakerNotebookInstanceKMSKeyConfigured
      Description: >-
        Check whether an AWS Key Management Service (KMS) key is configured for Amazon SageMaker notebook instance. 
        The rule is not NON_COMPLIANT if kmsKeyId is not specified for the Amazon SageMaker notebook instance.
      Scope: 
        ComplianceResourceTypes: 
        - "AWS::SageMaker::NotebookInstance"
      Source: 
        Owner: AWS
        SourceIdentifier: SAGEMAKER_NOTEBOOK_INSTANCE_KMS_KEY_CONFIGURED
      MaximumExecutionFrequency: Six_Hours