AWSTemplateFormatVersion: 2010-09-09
Description: Conformance Pack Deploy Template.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Baseline conformance pack details
        Parameters:
          - ConformancePackName
          - TemplateS3URI
          - DeliveryS3Bucket

Parameters:

  ConformancePackName:
    Description: "Conformance Pack Name"
    Default: S3ConformancePack
    Type: String

  TemplateS3URI:
    Description: "URI of the conformance pack template to be deployed."
    Default: s3://organization-repo/conformancepacks/CFS3ConformancePackTemplate.yml
    Type: String

  DeliveryS3Bucket:
    Description: "Delivery bucket where all conformance details are captured."
    Default : awsconfigconforms-848721808596 
    Type: String

Resources:

  TriggerLambda:
    Type: "Custom::TriggerLambda"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:848721808596:function:Governance-LFOrgConformancePack
      ConformancePackName: !Ref ConformancePackName
      DeliveryS3Bucket: !Ref DeliveryS3Bucket
      TemplateS3URI: !Ref TemplateS3URI